vincenzo = AthleteModel.where(name: 'Vincenzo Nibali').first_or_create(weight: 135, avatar: '')
taylor = AthleteModel.where(name: 'Taylor Phinney').first_or_create(weight: 165, avatar: '')
alex = AthleteModel.where(name: 'Alex Howes').first_or_create(weight: 145, avatar: '')
kiel = AthleteModel.where(name: 'Kiel Reijnen').first_or_create(weight: 139, avatar: '')
mara = AthleteModel.where(name: 'Mara Abbott').first_or_create(weight: 105, avatar: '')

ActivityModel.where(athlete_id: vincenzo.id, distance: 104).first_or_create(started_at: 7.days.ago, finished_at: 7.days.ago + 4.hours, elevation_gain: 5433)
ActivityModel.where(athlete_id: vincenzo.id, distance: 23).first_or_create(started_at: 6.days.ago, finished_at: 6.days.ago + 1.hours, elevation_gain: 205)
ActivityModel.where(athlete_id: vincenzo.id, distance: 156).first_or_create(started_at: 4.days.ago, finished_at: 4.days.ago + 6.hours, elevation_gain: 12398)
ActivityModel.where(athlete_id: vincenzo.id, distance: 82).first_or_create(started_at: 3.days.ago, finished_at: 3.days.ago + 3.hours, elevation_gain: 388)
ActivityModel.where(athlete_id: vincenzo.id, distance: 97).first_or_create(started_at: 1.days.ago, finished_at: 1.days.ago + 4.hours, elevation_gain: 3022)

ActivityModel.where(athlete_id: taylor.id, distance: 105).first_or_create(started_at: 7.days.ago, finished_at: 7.days.ago + 4.hours, elevation_gain: 5433)
ActivityModel.where(athlete_id: taylor.id, distance: 23).first_or_create(started_at: 6.days.ago, finished_at: 6.days.ago + 1.hours, elevation_gain: 205)
ActivityModel.where(athlete_id: taylor.id, distance: 156).first_or_create(started_at: 4.days.ago, finished_at: 4.days.ago + 6.hours, elevation_gain: 12398)
ActivityModel.where(athlete_id: taylor.id, distance: 82).first_or_create(started_at: 3.days.ago, finished_at: 3.days.ago + 3.hours, elevation_gain: 388)
ActivityModel.where(athlete_id: taylor.id, distance: 97).first_or_create(started_at: 1.days.ago, finished_at: 1.days.ago + 4.hours, elevation_gain: 3022)

ActivityModel.where(athlete_id: alex.id, distance: 105).first_or_create(started_at: 7.days.ago, finished_at: 7.days.ago + 4.hours, elevation_gain: 5433)
ActivityModel.where(athlete_id: alex.id, distance: 23).first_or_create(started_at: 6.days.ago, finished_at: 6.days.ago + 1.hours, elevation_gain: 205)
ActivityModel.where(athlete_id: alex.id, distance: 156).first_or_create(started_at: 4.days.ago, finished_at: 4.days.ago + 6.hours, elevation_gain: 12398)
ActivityModel.where(athlete_id: alex.id, distance: 82).first_or_create(started_at: 3.days.ago, finished_at: 3.days.ago + 3.hours, elevation_gain: 388)
ActivityModel.where(athlete_id: alex.id, distance: 97).first_or_create(started_at: 1.days.ago, finished_at: 1.days.ago + 4.hours, elevation_gain: 3022)

ActivityModel.where(athlete_id: kiel.id, distance: 106).first_or_create(started_at: 7.days.ago, finished_at: 7.days.ago + 4.hours, elevation_gain: 5433)
ActivityModel.where(athlete_id: kiel.id, distance: 23).first_or_create(started_at: 6.days.ago, finished_at: 6.days.ago + 1.hours, elevation_gain: 205)
ActivityModel.where(athlete_id: kiel.id, distance: 156).first_or_create(started_at: 4.days.ago, finished_at: 4.days.ago + 6.hours, elevation_gain: 12398)
ActivityModel.where(athlete_id: kiel.id, distance: 82).first_or_create(started_at: 3.days.ago, finished_at: 3.days.ago + 3.hours, elevation_gain: 388)
ActivityModel.where(athlete_id: kiel.id, distance: 97).first_or_create(started_at: 1.days.ago, finished_at: 1.days.ago + 4.hours, elevation_gain: 3022)

ActivityModel.where(athlete_id: mara.id, distance: 107).first_or_create(started_at: 7.days.ago, finished_at: 7.days.ago + 4.hours, elevation_gain: 5433)
ActivityModel.where(athlete_id: mara.id, distance: 23).first_or_create(started_at: 6.days.ago, finished_at: 6.days.ago + 1.hours, elevation_gain: 205)
ActivityModel.where(athlete_id: mara.id, distance: 156).first_or_create(started_at: 4.days.ago, finished_at: 4.days.ago + 6.hours, elevation_gain: 12398)
ActivityModel.where(athlete_id: mara.id, distance: 82).first_or_create(started_at: 3.days.ago, finished_at: 3.days.ago + 3.hours, elevation_gain: 388)
ActivityModel.where(athlete_id: mara.id, distance: 97).first_or_create(started_at: 1.days.ago, finished_at: 1.days.ago + 4.hours, elevation_gain: 3022)